### ISSUE TITLE
Can't manufacture MK4 or MK5 tiers

### ISSUE THREAD

**Issue by CremionisD** [brgmnn/factorio-power-armor#2]
I was trying to build MK4 armor, which requires two of the MK3's. Unforunately, the MK3's don't stack so I'm unable to put the two MK3 armors into the assembling machine. Either I'm missing something, or there is an issue.

**Comment by aideenfb** [comment]
Bug Confirmed...

**Comment by brgmnn** [comment]
Thanks for posting this, I apologize this was sloppy testing on my part. I just got to the point where I could craft the armor myself! I have updated the mod to only require one of each previous armor in the recipes.
